---

- hosts: all

  tasks:
    - name: copy - Copies files to remote locations <<http://docs.ansible.com/ansible/latest/modules/copy_module.html>>
      copy:
        src: ../files/chk-sha256sum.sh
        dest: /root/kvm/chk-sha256sum.sh
        mode: 0755
