---
- hosts: all

  tasks:
    - name: group - Add or remove groups <<http://docs.ansible.com/ansible/latest/modules/group_module.html>>
      group: 
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      with_items:
        - { name: oinstall, gid: 54321 }
        - { name: dba, gid: 54322 }
        - { name: asmdba, gid: 54323 }
        - { name: asmoper, gid: 54324 }
        - { name: asmadmin, gid: 54325 }
        - { name: oper, gid: 54326 }
        - { name: backupdba, gid: 54327 }
        - { name: dgdba, gid: 54328 }
        - { name: kmdba, gid: 54329 }
        - { name: racdba, gid: 54330 }
