---

- hosts: all

  tasks:
    - name: file - Sets attributes of files <<http://docs.ansible.com/ansible/latest/modules/file_module.html#author>>
      file:
        dest: /u01/app/oraInventory
        state: directory
        owner: oracle
        group: oinstall
        mode: 0775
