---

- hosts: all

  tasks:
    - name: mkdir /u01/app/oraInventory
      file:
        dest: /u01/app/oraInventory
        state: directory
        owner: oracle
        group: oinstall
        mode: 0775
