---

- hosts: all

  tasks:
    - name: shell - Execute commands in nodes. <<http://docs.ansible.com/ansible/latest/modules/shell_module.html>>
      shell: brctl show | grep "^br0"
      ignore_error: True
      register: brctl_show
      failed_when: brctl_show.rc not in [0, 1]
    - name:                                   表示
      debug: var=brctl_show.rc
