---
- hosts: all
  become: True
  become_user: oracle

  tasks:
    - name: unarchive - Unpacks an archive after (optionally) copying it from the local machine. <<http://docs.ansible.com/ansible/latest/modules/unarchive_module.html>>
      unarchive
        src: ../files/linuxx64_12201_database.zip
        dest: /home/oracle
