---
- hosts: all

  tasks:
    - name: user - Manage user accounts <<http://docs.ansible.com/ansible/latest/modules/user_module.html>>
      user:
        name: oracle
        uid: 54321
        group: oinstall
        groups: dba,asmdba,asmoper,asmadmin,oper,backupdba,dgdba,kmdba,racdba
        password: oracle
